name: static analyses
on: push
env:
  MIX_ENV: test
jobs:
  static:
    runs-on: ubuntu-latest
    name: Test Erlang/OTP ${{ matrix.otp }} & Elixir ${{ matrix.elixir }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1
        with:
          otp-version: 23.2.1
          elixir-version: 1.11.2
      - uses: actions/cache@v2
        with:
          path: |
            _build
            deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
      - run: mix deps.get
      - run: mix compile --warnings-as-errors
      - run: mix coveralls.json
        if: always()
      # - uses: codecov/codecov-action@v1
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     file: ./cover/excoveralls.json
      #   if: always()
      - run: mix credo
        if: always()
      - run: mix format --check-formatted
        if: always()
      - run: mix dialyzer
        if: always()
        